mongodb:
  test_db:
    addr: localhost:27017,localhost:27027,localhost:27037
    user:
    password:
    rs: rs0
    db:
web:
  port: 8888
rpc:
  port: 9403
kafka:
  addrs:
    - localhost:9092
  version: 2.6.0
  group:
click_house:
  addrs:
    - localhost:9000
  user:
  password:
  db:

image_path: D:\EEG\sub03-pangrichong-250709\cam\test\lbb
ws_addr: ws://172.19.202.20:18765/ws
client_num: 5  #最大设置5个
interval: 10