// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_any.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestAny struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestAny) Reset()         { *m = TestAny{} }
func (m *TestAny) String() string { return proto.CompactTextString(m) }
func (*TestAny) ProtoMessage()    {}
func (*TestAny) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa204ece5f8bacf, []int{0}
}

func (m *TestAny) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAny.Unmarshal(m, b)
}
func (m *TestAny) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAny.Marshal(b, m, deterministic)
}
func (m *TestAny) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAny.Merge(m, src)
}
func (m *TestAny) XXX_Size() int {
	return xxx_messageInfo_TestAny.Size(m)
}
func (m *TestAny) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAny.DiscardUnknown(m)
}

var xxx_messageInfo_TestAny proto.InternalMessageInfo

func (m *TestAny) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestAny) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TestAny) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Response struct {
	Code                 uint32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 *anypb.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_faa204ece5f8bacf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() *anypb.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TestAny)(nil), "protobuf.TestAny")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
}

func init() { proto.RegisterFile("test_any.proto", fileDescriptor_faa204ece5f8bacf) }

var fileDescriptor_faa204ece5f8bacf = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x31, 0x6b, 0x87, 0x30,
	0x10, 0xc5, 0xd1, 0xbf, 0xad, 0xf6, 0x44, 0x29, 0x87, 0x43, 0xda, 0x49, 0x9c, 0x9c, 0x22, 0xb4,
	0x9f, 0xc0, 0x3a, 0x39, 0x74, 0x09, 0x4e, 0x2e, 0x45, 0xc9, 0x55, 0x0a, 0x92, 0x48, 0x73, 0x1d,
	0xfc, 0xf6, 0xa5, 0xb1, 0x3a, 0xdd, 0xbb, 0xc7, 0xe3, 0xc7, 0x0f, 0x72, 0x26, 0xc7, 0x1f, 0x93,
	0xd9, 0xe5, 0xf6, 0x6d, 0xd9, 0x62, 0xe2, 0xcf, 0xfc, 0xf3, 0xf9, 0xfc, 0xb4, 0x58, 0xbb, 0xac,
	0xd4, 0x9c, 0x45, 0x73, 0x8d, 0xaa, 0x1e, 0xe2, 0x81, 0x1c, 0xb7, 0x66, 0xc7, 0x1c, 0xc2, 0x5e,
	0x8b, 0xa0, 0x0c, 0xea, 0x48, 0x85, 0xbd, 0xc6, 0x02, 0xee, 0x86, 0x2f, 0x5e, 0x49, 0x84, 0x65,
	0x50, 0x3f, 0xa8, 0xe3, 0x41, 0x01, 0x71, 0x67, 0x0d, 0x93, 0x61, 0x71, 0xf3, 0xfd, 0xf9, 0x56,
	0x23, 0x24, 0x8a, 0xdc, 0x66, 0x8d, 0x23, 0x44, 0x88, 0x3a, 0xab, 0xc9, 0xd3, 0x32, 0xe5, 0x33,
	0x3e, 0xc2, 0xed, 0xdd, 0x2d, 0xff, 0xb4, 0xbf, 0x88, 0x35, 0x44, 0x7a, 0xe2, 0xc9, 0x83, 0xd2,
	0x97, 0x42, 0x1e, 0x9a, 0xf2, 0xd4, 0x94, 0xad, 0xd9, 0x95, 0x5f, 0xbc, 0x65, 0x63, 0x2a, 0xe5,
	0xe5, 0x3f, 0xdf, 0xfb, 0xf4, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xe4, 0x9b, 0xb5, 0xf3,
	0x00, 0x00, 0x00,
}
