// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wiref

import (
	"github.com/google/wire"
	"go-lab/app/go_wire/internal/model"
)

// Injectors from wire.go:

func InitMission(name string) model.Mission {
	player := model.NewPlayer(name)
	monster := model.NewMonster()
	mission := model.NewMission(player, monster)
	return mission
}

func InitMissionWithValue(name string) model.Mission {
	player := model.NewPlayer(name)
	monster := _wireMonsterValue
	mission := model.NewMission(player, monster)
	return mission
}

var (
	_wireMonsterValue = kitty
)

func InitMissionWithParam(p model.PlayerParam, m model.MonsterParam) model.Mission {
	player := model.NewPlayerWithParam(p)
	monster := model.NewMonsterWithParam(m)
	mission := model.NewMission(player, monster)
	return mission
}

func InitMissionWithParamSet(p model.PlayerParam, m model.MonsterParam) model.Mission {
	player := model.NewPlayerWithParam(p)
	monster := model.NewMonsterWithParam(m)
	mission := model.NewMission(player, monster)
	return mission
}

// wire.go:

var kitty = model.Monster{Name: "kitty"}

var monsterPlayerSet = wire.NewSet(model.NewMonsterWithParam, model.NewPlayerWithParam)
