apiVersion: v1
kind: Service
metadata:
  labels:
    app: gin-web-bak
  name: gin-web-bak
  namespace: default
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8888
  selector:
    app: gin-web-bak
  type: LoadBalancer